// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RRPAYRROL_SYSTEM.Models;

#nullable disable

namespace RRPAYRROL_SYSTEM.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RRPAYRROL_SYSTEM.Models.Actividad", b =>
                {
                    b.Property<int>("IdActividad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdActividad"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("PagadaPorHora")
                        .HasColumnType("bit");

                    b.Property<decimal>("TarifaMinima")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdActividad");

                    b.ToTable("Actividades");
                });

            modelBuilder.Entity("RRPAYRROL_SYSTEM.Models.ActividadAsignada", b =>
                {
                    b.Property<int>("IdActividadAsignada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdActividadAsignada"));

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdActividad")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpleadoProyectoFK")
                        .HasColumnType("int");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int");

                    b.HasKey("IdActividadAsignada");

                    b.HasIndex("IdActividad");

                    b.HasIndex("IdEmpleadoProyectoFK");

                    b.HasIndex("IdEstado");

                    b.ToTable("ActividadesAsignadas");
                });

            modelBuilder.Entity("RRPAYRROL_SYSTEM.Models.Asistencia", b =>
                {
                    b.Property<int>("IdAsistencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAsistencia"));

                    b.Property<DateTime>("FechaEntrada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSalida")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int>("IdProyecto")
                        .HasColumnType("int");

                    b.HasKey("IdAsistencia");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdProyecto");

                    b.ToTable("Asistencias");
                });

            modelBuilder.Entity("RRPAYRROL_SYSTEM.Models.Ausencia", b =>
                {
                    b.Property<int>("IdAusencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAusencia"));

                    b.Property<DateTime>("FechaAusencia")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEmpleadoFK")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Pagado")
                        .HasColumnType("bit");

                    b.HasKey("IdAusencia");

                    b.ToTable("Ausencias");
                });

            modelBuilder.Entity("RRPAYRROL_SYSTEM.Models.Concepto", b =>
                {
                    b.Property<int>("IdConcepto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConcepto"));

                    b.Property<int?>("DetalleNominaIdDetalleNomina")
                        .HasColumnType("int");

                    b.Property<int>("IdDetalleNominaFK")
                        .HasColumnType("int");

                    b.Property<decimal?>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NombreConcepto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Porcentaje")
                        .HasColumnType("real");

                    b.Property<bool>("Tipo")
                        .HasColumnType("bit");

                    b.HasKey("IdConcepto");

                    b.HasIndex("DetalleNominaIdDetalleNomina");

                    b.ToTable("Conceptos");
                });

            modelBuilder.Entity("RRPAYRROL_SYSTEM.Models.Contrato", b =>
                {
                    b.Property<int>("IdContrato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdContrato"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Documento")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("FechaContratacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRenovacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("IdContrato");

                    b.ToTable("Contratos");
                });

            modelBuilder.Entity("RRPAYRROL_SYSTEM.Models.DetalleNomina", b =>
                {
                    b.Property<int>("IdDetalleNomina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalleNomina"));

                    b.Property<decimal>("AFP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Beneficios")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Cargo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DeduccionesInternas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Empleado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ISR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IdNomina")
                        .HasColumnType("int");

                    b.Property<decimal>("SFS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SueldoBruto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SueldoNeto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdDetalleNomina");

                    b.ToTable("DetallesNominas");
                });

            modelBuilder.Entity("RRPAYRROL_SYSTEM.Models.Empleado", b =>
                {
                    b.Property<int>("IdEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpleado"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ContratoIdContrato")
                        .HasColumnType("int");

                    b.Property<int>("CreadoPor")
                        .HasColumnType("int");

                    b.Property<int?>("CreadoPorUsuarioIdUsuario")
                        .HasColumnType("int");

                    b.Property<int?>("EstadoIdEstado")
                        .HasColumnType("int");

                    b.Property<int>("IdContratoFK")
                        .HasColumnType("int");

                    b.Property<int>("IdEstadoFK")
                        .HasColumnType("int");

                    b.Property<int>("IdPersonaFK")
                        .HasColumnType("int");

                    b.Property<int>("IdPuestoFK")
                        .HasColumnType("int");

                    b.Property<int>("ModificadoPor")
                        .HasColumnType("int");

                    b.Property<int?>("ModificadoPorUsuarioIdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("NumDeCuenta")
                        .HasColumnType("int");

                    b.Property<int?>("PersonaIdPersona")
                        .HasColumnType("int");

                    b.Property<int?>("PuestoIdPuesto")
                        .HasColumnType("int");

                    b.HasKey("IdEmpleado");

                    b.HasIndex("ContratoIdContrato");

                    b.HasIndex("CreadoPorUsuarioIdUsuario");

                    b.HasIndex("EstadoIdEstado");

                    b.HasIndex("ModificadoPorUsuarioIdUsuario");

                    b.HasIndex("PersonaIdPersona");

                    b.HasIndex("PuestoIdPuesto");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("RRPAYRROL_SYSTEM.Models.EmpleadoProyecto", b =>
                {
                    b.Property<int>("IdEmpleadoProyecto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpleadoProyecto"));

                    b.Property<bool>("EsEncargado")
                        .HasColumnType("bit");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("IdProyecto")
                        .HasColumnType("int");

                    b.HasKey("IdEmpleadoProyecto");

                    b.ToTable("EmpleadoProyectos");
                });

            modelBuilder.Entity("RRPAYRROL_SYSTEM.Models.Estado", b =>
                {
                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstado"));

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdEstado");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("RRPAYRROL_SYSTEM.Models.Municipio", b =>
                {
                    b.Property<int>("IdMunicipio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMunicipio"));

                    b.Property<string>("NombreMunicipio")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMunicipio");

                    b.ToTable("Municipios");
                });

            modelBuilder.Entity("RRPAYRROL_SYSTEM.Models.Nacionalidad", b =>
                {
                    b.Property<int>("IdNacionalidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNacionalidad"));

                    b.Property<string>("nacionalidad")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("IdNacionalidad");

                    b.ToTable("Nacionalidades");
                });

            modelBuilder.Entity("RRPAYRROL_SYSTEM.Models.Nomina", b =>
                {
                    b.Property<int>("IdNomina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNomina"));

                    b.Property<int>("CreadoPor")
                        .HasColumnType("int");

                    b.Property<int?>("CreadoPorUsuarioIdUsuario")
                        .HasColumnType("int");

                    b.Property<int?>("EstadoIdEstado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCorte")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int>("IdProyecto")
                        .HasColumnType("int");

                    b.Property<int>("ModificadoPor")
                        .HasColumnType("int");

                    b.Property<int?>("ModificadoPorUsuarioIdUsuario")
                        .HasColumnType("int");

                    b.Property<int?>("ProyectoIdProyecto")
                        .HasColumnType("int");

                    b.HasKey("IdNomina");

                    b.HasIndex("CreadoPorUsuarioIdUsuario");

                    b.HasIndex("EstadoIdEstado");

                    b.HasIndex("ModificadoPorUsuarioIdUsuario");

                    b.HasIndex("ProyectoIdProyecto");

                    b.ToTable("Nominas");
                });

            modelBuilder.Entity("RRPAYRROL_SYSTEM.Models.Pago", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPago"));

                    b.Property<decimal>("Comision")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CreadoPor")
                        .HasColumnType("int");

                    b.Property<int?>("CreadoPorUsuarioIdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Emisor")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Empleado")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEmpleadoFK")
                        .HasColumnType("int");

                    b.Property<int>("IdEstadoFK")
                        .HasColumnType("int");

                    b.Property<int>("IdNominaFK")
                        .HasColumnType("int");

                    b.Property<int>("ModificadoPor")
                        .HasColumnType("int");

                    b.Property<int?>("ModificadoPorUsuarioIdUsuario")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("empleadoIdEmpleado")
                        .HasColumnType("int");

                    b.HasKey("IdPago");

                    b.HasIndex("CreadoPorUsuarioIdUsuario");

                    b.HasIndex("IdEstadoFK");

                    b.HasIndex("IdNominaFK");

                    b.HasIndex("ModificadoPorUsuarioIdUsuario");

                    b.HasIndex("empleadoIdEmpleado");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("RRPAYRROL_SYSTEM.Models.Persona", b =>
                {
                    b.Property<int>("IdPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPersona"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Celular")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<int>("CreadoPor")
                        .HasColumnType("int");

                    b.Property<int?>("CreadoPorUsuarioIdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdMunicipioFK")
                        .HasColumnType("int");

                    b.Property<int>("IdNacionalidadFK")
                        .HasColumnType("int");

                    b.Property<int>("IdProvinciaFK")
                        .HasColumnType("int");

                    b.Property<int>("ModificadoPor")
                        .HasColumnType("int");

                    b.Property<int?>("ModificadoPorUsuarioIdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("IdPersona");

                    b.HasIndex("CreadoPorUsuarioIdUsuario");

                    b.HasIndex("IdMunicipioFK");

                    b.HasIndex("IdNacionalidadFK");

                    b.HasIndex("IdProvinciaFK");

                    b.HasIndex("ModificadoPorUsuarioIdUsuario");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("RRPAYRROL_SYSTEM.Models.Provincia", b =>
                {
                    b.Property<int>("IdProvincia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProvincia"));

                    b.Property<string>("NombreProvincia")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProvincia");

                    b.ToTable("Provincias");
                });

            modelBuilder.Entity("RRPAYRROL_SYSTEM.Models.Proyecto", b =>
                {
                    b.Property<int>("IdProyecto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProyecto"));

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int>("IdPersonaFK")
                        .HasColumnType("int");

                    b.Property<string>("Localizacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdProyecto");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdPersonaFK");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("RRPAYRROL_SYSTEM.Models.Puesto", b =>
                {
                    b.Property<int>("IdPuesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPuesto"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("IdPuesto");

                    b.ToTable("Puestos");
                });

            modelBuilder.Entity("RRPAYRROL_SYSTEM.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("RRPAYRROL_SYSTEM.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Contrasena")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int>("IdPersona")
                        .HasColumnType("int");

                    b.Property<string>("NombreUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("RRPAYRROL_SYSTEM.Models.UsuarioRol", b =>
                {
                    b.Property<int>("IdUsuarioRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuarioRol"));

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdUsuarioRol");

                    b.ToTable("UsuarioRoles");
                });

            modelBuilder.Entity("RRPAYRROL_SYSTEM.Models.ActividadAsignada", b =>
                {
                    b.HasOne("RRPAYRROL_SYSTEM.Models.Actividad", "Actividad")
                        .WithMany()
                        .HasForeignKey("IdActividad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RRPAYRROL_SYSTEM.Models.EmpleadoProyecto", "EmpleadoProyecto")
                        .WithMany()
                        .HasForeignKey("IdEmpleadoProyectoFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RRPAYRROL_SYSTEM.Models.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actividad");

                    b.Navigation("EmpleadoProyecto");

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("RRPAYRROL_SYSTEM.Models.Asistencia", b =>
                {
                    b.HasOne("RRPAYRROL_SYSTEM.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RRPAYRROL_SYSTEM.Models.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RRPAYRROL_SYSTEM.Models.Proyecto", "Proyecto")
                        .WithMany()
                        .HasForeignKey("IdProyecto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Estado");

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("RRPAYRROL_SYSTEM.Models.Concepto", b =>
                {
                    b.HasOne("RRPAYRROL_SYSTEM.Models.DetalleNomina", "DetalleNomina")
                        .WithMany()
                        .HasForeignKey("DetalleNominaIdDetalleNomina");

                    b.Navigation("DetalleNomina");
                });

            modelBuilder.Entity("RRPAYRROL_SYSTEM.Models.Empleado", b =>
                {
                    b.HasOne("RRPAYRROL_SYSTEM.Models.Contrato", "Contrato")
                        .WithMany()
                        .HasForeignKey("ContratoIdContrato");

                    b.HasOne("RRPAYRROL_SYSTEM.Models.Usuario", "CreadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("CreadoPorUsuarioIdUsuario");

                    b.HasOne("RRPAYRROL_SYSTEM.Models.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoIdEstado");

                    b.HasOne("RRPAYRROL_SYSTEM.Models.Usuario", "ModificadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("ModificadoPorUsuarioIdUsuario");

                    b.HasOne("RRPAYRROL_SYSTEM.Models.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaIdPersona");

                    b.HasOne("RRPAYRROL_SYSTEM.Models.Puesto", "Puesto")
                        .WithMany()
                        .HasForeignKey("PuestoIdPuesto");

                    b.Navigation("Contrato");

                    b.Navigation("CreadoPorUsuario");

                    b.Navigation("Estado");

                    b.Navigation("ModificadoPorUsuario");

                    b.Navigation("Persona");

                    b.Navigation("Puesto");
                });

            modelBuilder.Entity("RRPAYRROL_SYSTEM.Models.Nomina", b =>
                {
                    b.HasOne("RRPAYRROL_SYSTEM.Models.Usuario", "CreadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("CreadoPorUsuarioIdUsuario");

                    b.HasOne("RRPAYRROL_SYSTEM.Models.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoIdEstado");

                    b.HasOne("RRPAYRROL_SYSTEM.Models.Usuario", "ModificadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("ModificadoPorUsuarioIdUsuario");

                    b.HasOne("RRPAYRROL_SYSTEM.Models.Proyecto", "Proyecto")
                        .WithMany()
                        .HasForeignKey("ProyectoIdProyecto");

                    b.Navigation("CreadoPorUsuario");

                    b.Navigation("Estado");

                    b.Navigation("ModificadoPorUsuario");

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("RRPAYRROL_SYSTEM.Models.Pago", b =>
                {
                    b.HasOne("RRPAYRROL_SYSTEM.Models.Usuario", "CreadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("CreadoPorUsuarioIdUsuario");

                    b.HasOne("RRPAYRROL_SYSTEM.Models.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("IdEstadoFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RRPAYRROL_SYSTEM.Models.Nomina", "Nomina")
                        .WithMany()
                        .HasForeignKey("IdNominaFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RRPAYRROL_SYSTEM.Models.Usuario", "ModificadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("ModificadoPorUsuarioIdUsuario");

                    b.HasOne("RRPAYRROL_SYSTEM.Models.Empleado", "empleado")
                        .WithMany()
                        .HasForeignKey("empleadoIdEmpleado");

                    b.Navigation("CreadoPorUsuario");

                    b.Navigation("Estado");

                    b.Navigation("ModificadoPorUsuario");

                    b.Navigation("Nomina");

                    b.Navigation("empleado");
                });

            modelBuilder.Entity("RRPAYRROL_SYSTEM.Models.Persona", b =>
                {
                    b.HasOne("RRPAYRROL_SYSTEM.Models.Usuario", "CreadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("CreadoPorUsuarioIdUsuario");

                    b.HasOne("RRPAYRROL_SYSTEM.Models.Municipio", "Municipio")
                        .WithMany()
                        .HasForeignKey("IdMunicipioFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RRPAYRROL_SYSTEM.Models.Nacionalidad", "Nacionalidad")
                        .WithMany()
                        .HasForeignKey("IdNacionalidadFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RRPAYRROL_SYSTEM.Models.Provincia", "Provincia")
                        .WithMany()
                        .HasForeignKey("IdProvinciaFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RRPAYRROL_SYSTEM.Models.Usuario", "ModificadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("ModificadoPorUsuarioIdUsuario");

                    b.Navigation("CreadoPorUsuario");

                    b.Navigation("ModificadoPorUsuario");

                    b.Navigation("Municipio");

                    b.Navigation("Nacionalidad");

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("RRPAYRROL_SYSTEM.Models.Proyecto", b =>
                {
                    b.HasOne("RRPAYRROL_SYSTEM.Models.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RRPAYRROL_SYSTEM.Models.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("IdPersonaFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Persona");
                });
#pragma warning restore 612, 618
        }
    }
}
